"""Constantes y enumeraciones del protocolo EC (External Connection) de aMule.

Port directo de ``jamule/ec/Codes.kt``. Los valores numéricos se corresponden
exactamente con los definidos por aMule en ``ECCodes.h`` / ``ECTagTypes.h``, por
lo que **no deben modificarse** sin verificar el origen.

Nota sobre tipos: Kotlin distingue ``UByte``/``UShort``/``UInt``/``ULong`` con
overflow controlado. En Python todos los enteros son arbitrariamente grandes,
así que aquí guardamos los valores como ``int`` y delegamos el truncado a la
capa de codificación (:mod:`amarr.jamule.ec.encoding`).
"""

from __future__ import annotations

from enum import Enum


class ProtocolVersion(Enum):
    """Versión del protocolo EC soportada (aMule 2.3.1 - 2.3.3)."""

    EC_CURRENT_PROTOCOL_VERSION = 0x0204


class ECFlag(Enum):
    """Flags de transmisión de un paquete EC."""

    EC_FLAG_ZLIB = 0x00000001
    EC_FLAG_UTF8_NUMBERS = 0x00000002
    EC_FLAG_HAS_ID = 0x00000004
    EC_FLAG_ACCEPTS = 0x00000010
    EC_FLAG_UNKNOWN_MASK = 0xFF7F7F08


class ECOpCode(Enum):
    """Códigos de operación de los paquetes EC.

    Solo se usan unos pocos en amarr, pero se incluyen todos para mantener la
    paridad con la librería original y facilitar futuras ampliaciones.
    """

    EC_OP_NOOP = 0x01
    EC_OP_AUTH_REQ = 0x02
    EC_OP_AUTH_FAIL = 0x03
    EC_OP_AUTH_OK = 0x04
    EC_OP_FAILED = 0x05
    EC_OP_STRINGS = 0x06
    EC_OP_MISC_DATA = 0x07
    EC_OP_SHUTDOWN = 0x08
    EC_OP_ADD_LINK = 0x09
    EC_OP_STAT_REQ = 0x0A
    EC_OP_GET_CONNSTATE = 0x0B
    EC_OP_STATS = 0x0C
    EC_OP_GET_DLOAD_QUEUE = 0x0D
    EC_OP_GET_ULOAD_QUEUE = 0x0E
    EC_OP_GET_SHARED_FILES = 0x10
    EC_OP_SHARED_SET_PRIO = 0x11
    EC_OP_PARTFILE_SWAP_A4AF_THIS = 0x16
    EC_OP_PARTFILE_SWAP_A4AF_THIS_AUTO = 0x17
    EC_OP_PARTFILE_SWAP_A4AF_OTHERS = 0x18
    EC_OP_PARTFILE_PAUSE = 0x19
    EC_OP_PARTFILE_RESUME = 0x1A
    EC_OP_PARTFILE_STOP = 0x1B
    EC_OP_PARTFILE_PRIO_SET = 0x1C
    EC_OP_PARTFILE_DELETE = 0x1D
    EC_OP_PARTFILE_SET_CAT = 0x1E
    EC_OP_DLOAD_QUEUE = 0x1F
    EC_OP_ULOAD_QUEUE = 0x20
    EC_OP_SHARED_FILES = 0x22
    EC_OP_SHAREDFILES_RELOAD = 0x23
    EC_OP_RENAME_FILE = 0x25
    EC_OP_SEARCH_START = 0x26
    EC_OP_SEARCH_STOP = 0x27
    EC_OP_SEARCH_RESULTS = 0x28
    EC_OP_SEARCH_PROGRESS = 0x29
    EC_OP_DOWNLOAD_SEARCH_RESULT = 0x2A
    EC_OP_IPFILTER_RELOAD = 0x2B
    EC_OP_GET_SERVER_LIST = 0x2C
    EC_OP_SERVER_LIST = 0x2D
    EC_OP_SERVER_DISCONNECT = 0x2E
    EC_OP_SERVER_CONNECT = 0x2F
    EC_OP_SERVER_REMOVE = 0x30
    EC_OP_SERVER_ADD = 0x31
    EC_OP_SERVER_UPDATE_FROM_URL = 0x32
    EC_OP_ADDLOGLINE = 0x33
    EC_OP_ADDDEBUGLOGLINE = 0x34
    EC_OP_GET_LOG = 0x35
    EC_OP_GET_DEBUGLOG = 0x36
    EC_OP_GET_SERVERINFO = 0x37
    EC_OP_LOG = 0x38
    EC_OP_DEBUGLOG = 0x39
    EC_OP_SERVERINFO = 0x3A
    EC_OP_RESET_LOG = 0x3B
    EC_OP_RESET_DEBUGLOG = 0x3C
    EC_OP_CLEAR_SERVERINFO = 0x3D
    EC_OP_GET_LAST_LOG_ENTRY = 0x3E
    EC_OP_GET_PREFERENCES = 0x3F
    EC_OP_SET_PREFERENCES = 0x40
    EC_OP_CREATE_CATEGORY = 0x41
    EC_OP_UPDATE_CATEGORY = 0x42
    EC_OP_DELETE_CATEGORY = 0x43
    EC_OP_GET_STATSGRAPHS = 0x44
    EC_OP_STATSGRAPHS = 0x45
    EC_OP_GET_STATSTREE = 0x46
    EC_OP_STATSTREE = 0x47
    EC_OP_KAD_START = 0x48
    EC_OP_KAD_STOP = 0x49
    EC_OP_CONNECT = 0x4A
    EC_OP_DISCONNECT = 0x4B
    EC_OP_KAD_UPDATE_FROM_URL = 0x4D
    EC_OP_KAD_BOOTSTRAP_FROM_IP = 0x4E
    EC_OP_AUTH_SALT = 0x4F
    EC_OP_AUTH_PASSWD = 0x50
    EC_OP_IPFILTER_UPDATE = 0x51
    EC_OP_GET_UPDATE = 0x52
    EC_OP_CLEAR_COMPLETED = 0x53
    EC_OP_CLIENT_SWAP_TO_ANOTHER_FILE = 0x54
    EC_OP_SHARED_FILE_SET_COMMENT = 0x55
    EC_OP_SERVER_SET_STATIC_PRIO = 0x56
    EC_OP_FRIEND = 0x57

    @classmethod
    def from_value(cls, value: int) -> "ECOpCode":
        """Equivalente a ``ECOpCode.fromValue``; lanza si el código es desconocido."""
        return cls(value)


class ECTagName(Enum):
    """Nombres de tag del protocolo EC.

    A diferencia de :class:`ECOpCode`, un valor desconocido **no** es un error:
    se mapea a :attr:`EC_TAG_UNKNOWN` (igual que en jamule), porque aMule puede
    enviar tags que la librería no modela.
    """

    EC_TAG_STRING = 0x0000
    EC_TAG_PASSWD_HASH = 0x0001
    EC_TAG_PROTOCOL_VERSION = 0x0002
    EC_TAG_VERSION_ID = 0x0003
    EC_TAG_DETAIL_LEVEL = 0x0004
    EC_TAG_CONNSTATE = 0x0005
    EC_TAG_ED2K_ID = 0x0006
    EC_TAG_LOG_TO_STATUS = 0x0007
    EC_TAG_BOOTSTRAP_IP = 0x0008
    EC_TAG_BOOTSTRAP_PORT = 0x0009
    EC_TAG_CLIENT_ID = 0x000A
    EC_TAG_PASSWD_SALT = 0x000B
    EC_TAG_CAN_ZLIB = 0x000C
    EC_TAG_CAN_UTF8_NUMBERS = 0x000D
    EC_TAG_CAN_NOTIFY = 0x000E
    EC_TAG_ECID = 0x000F
    EC_TAG_KAD_ID = 0x0010
    EC_TAG_CLIENT_NAME = 0x0100
    EC_TAG_CLIENT_VERSION = 0x0101
    EC_TAG_CLIENT_MOD = 0x0102
    EC_TAG_STATS_UL_SPEED = 0x0200
    EC_TAG_STATS_DL_SPEED = 0x0201
    EC_TAG_STATS_UL_SPEED_LIMIT = 0x0202
    EC_TAG_STATS_DL_SPEED_LIMIT = 0x0203
    EC_TAG_STATS_UP_OVERHEAD = 0x0204
    EC_TAG_STATS_DOWN_OVERHEAD = 0x0205
    EC_TAG_STATS_TOTAL_SRC_COUNT = 0x0206
    EC_TAG_STATS_BANNED_COUNT = 0x0207
    EC_TAG_STATS_UL_QUEUE_LEN = 0x0208
    EC_TAG_STATS_ED2K_USERS = 0x0209
    EC_TAG_STATS_KAD_USERS = 0x020A
    EC_TAG_STATS_ED2K_FILES = 0x020B
    EC_TAG_STATS_KAD_FILES = 0x020C
    EC_TAG_STATS_LOGGER_MESSAGE = 0x020D
    EC_TAG_STATS_KAD_FIREWALLED_UDP = 0x020E
    EC_TAG_STATS_KAD_INDEXED_SOURCES = 0x020F
    EC_TAG_STATS_KAD_INDEXED_KEYWORDS = 0x0210
    EC_TAG_STATS_KAD_INDEXED_NOTES = 0x0211
    EC_TAG_STATS_KAD_INDEXED_LOAD = 0x0212
    EC_TAG_STATS_KAD_IP_ADRESS = 0x0213
    EC_TAG_STATS_BUDDY_STATUS = 0x0214
    EC_TAG_STATS_BUDDY_IP = 0x0215
    EC_TAG_STATS_BUDDY_PORT = 0x0216
    EC_TAG_STATS_KAD_IN_LAN_MODE = 0x0217
    EC_TAG_STATS_TOTAL_SENT_BYTES = 0x0218
    EC_TAG_STATS_TOTAL_RECEIVED_BYTES = 0x0219
    EC_TAG_STATS_SHARED_FILE_COUNT = 0x021A
    EC_TAG_STATS_KAD_NODES = 0x021B
    EC_TAG_PARTFILE = 0x0300
    EC_TAG_PARTFILE_NAME = 0x0301
    EC_TAG_PARTFILE_PARTMETID = 0x0302
    EC_TAG_PARTFILE_SIZE_FULL = 0x0303
    EC_TAG_PARTFILE_SIZE_XFER = 0x0304
    EC_TAG_PARTFILE_SIZE_XFER_UP = 0x0305
    EC_TAG_PARTFILE_SIZE_DONE = 0x0306
    EC_TAG_PARTFILE_SPEED = 0x0307
    EC_TAG_PARTFILE_STATUS = 0x0308
    EC_TAG_PARTFILE_PRIO = 0x0309
    EC_TAG_PARTFILE_SOURCE_COUNT = 0x030A
    EC_TAG_PARTFILE_SOURCE_COUNT_A4AF = 0x030B
    EC_TAG_PARTFILE_SOURCE_COUNT_NOT_CURRENT = 0x030C
    EC_TAG_PARTFILE_SOURCE_COUNT_XFER = 0x030D
    EC_TAG_PARTFILE_ED2K_LINK = 0x030E
    EC_TAG_PARTFILE_CAT = 0x030F
    EC_TAG_PARTFILE_LAST_RECV = 0x0310
    EC_TAG_PARTFILE_LAST_SEEN_COMP = 0x0311
    EC_TAG_PARTFILE_PART_STATUS = 0x0312
    EC_TAG_PARTFILE_GAP_STATUS = 0x0313
    EC_TAG_PARTFILE_REQ_STATUS = 0x0314
    EC_TAG_PARTFILE_SOURCE_NAMES = 0x0315
    EC_TAG_PARTFILE_COMMENTS = 0x0316
    EC_TAG_PARTFILE_STOPPED = 0x0317
    EC_TAG_PARTFILE_DOWNLOAD_ACTIVE = 0x0318
    EC_TAG_PARTFILE_LOST_CORRUPTION = 0x0319
    EC_TAG_PARTFILE_GAINED_COMPRESSION = 0x031A
    EC_TAG_PARTFILE_SAVED_ICH = 0x031B
    EC_TAG_PARTFILE_SOURCE_NAMES_COUNTS = 0x031C
    EC_TAG_PARTFILE_AVAILABLE_PARTS = 0x031D
    EC_TAG_PARTFILE_HASH = 0x031E
    EC_TAG_PARTFILE_SHARED = 0x031F
    EC_TAG_PARTFILE_HASHED_PART_COUNT = 0x0320
    EC_TAG_PARTFILE_A4AFAUTO = 0x0321
    EC_TAG_PARTFILE_A4AF_SOURCES = 0x0322
    EC_TAG_KNOWNFILE = 0x0400
    EC_TAG_KNOWNFILE_XFERRED = 0x0401
    EC_TAG_KNOWNFILE_XFERRED_ALL = 0x0402
    EC_TAG_KNOWNFILE_REQ_COUNT = 0x0403
    EC_TAG_KNOWNFILE_REQ_COUNT_ALL = 0x0404
    EC_TAG_KNOWNFILE_ACCEPT_COUNT = 0x0405
    EC_TAG_KNOWNFILE_ACCEPT_COUNT_ALL = 0x0406
    EC_TAG_KNOWNFILE_AICH_MASTERHASH = 0x0407
    EC_TAG_KNOWNFILE_FILENAME = 0x0408
    EC_TAG_KNOWNFILE_COMPLETE_SOURCES_LOW = 0x0409
    EC_TAG_KNOWNFILE_COMPLETE_SOURCES_HIGH = 0x040A
    EC_TAG_KNOWNFILE_PRIO = 0x040B
    EC_TAG_KNOWNFILE_ON_QUEUE = 0x040C
    EC_TAG_KNOWNFILE_COMPLETE_SOURCES = 0x040D
    EC_TAG_KNOWNFILE_COMMENT = 0x040E
    EC_TAG_KNOWNFILE_RATING = 0x040F
    EC_TAG_SERVER = 0x0500
    EC_TAG_SERVER_NAME = 0x0501
    EC_TAG_SERVER_DESC = 0x0502
    EC_TAG_SERVER_ADDRESS = 0x0503
    EC_TAG_SERVER_PING = 0x0504
    EC_TAG_SERVER_USERS = 0x0505
    EC_TAG_SERVER_USERS_MAX = 0x0506
    EC_TAG_SERVER_FILES = 0x0507
    EC_TAG_SERVER_PRIO = 0x0508
    EC_TAG_SERVER_FAILED = 0x0509
    EC_TAG_SERVER_STATIC = 0x050A
    EC_TAG_SERVER_VERSION = 0x050B
    EC_TAG_SERVER_IP = 0x050C
    EC_TAG_SERVER_PORT = 0x050D
    EC_TAG_CLIENT = 0x0600
    EC_TAG_SEARCHFILE = 0x0700
    EC_TAG_SEARCH_TYPE = 0x0701
    EC_TAG_SEARCH_NAME = 0x0702
    EC_TAG_SEARCH_MIN_SIZE = 0x0703
    EC_TAG_SEARCH_MAX_SIZE = 0x0704
    EC_TAG_SEARCH_FILE_TYPE = 0x0705
    EC_TAG_SEARCH_EXTENSION = 0x0706
    EC_TAG_SEARCH_AVAILABILITY = 0x0707
    EC_TAG_SEARCH_STATUS = 0x0708
    EC_TAG_SEARCH_PARENT = 0x0709
    EC_TAG_SELECT_PREFS = 0x1000
    EC_TAG_PREFS_CATEGORIES = 0x1100
    EC_TAG_CATEGORY = 0x1101
    EC_TAG_CATEGORY_TITLE = 0x1102
    EC_TAG_CATEGORY_PATH = 0x1103
    EC_TAG_CATEGORY_COMMENT = 0x1104
    EC_TAG_CATEGORY_COLOR = 0x1105
    EC_TAG_CATEGORY_PRIO = 0x1106
    EC_TAG_UNKNOWN = 0xFFFF

    @classmethod
    def from_value(cls, value: int) -> "ECTagName":
        """Igual que ``ECTagName.fromValue``: desconocido -> ``EC_TAG_UNKNOWN``."""
        try:
            return cls(value)
        except ValueError:
            return cls.EC_TAG_UNKNOWN


class ECDetailLevel(Enum):
    EC_DETAIL_CMD = 0x00
    EC_DETAIL_WEB = 0x01
    EC_DETAIL_FULL = 0x02
    EC_DETAIL_UPDATE = 0x03
    EC_DETAIL_INC_UPDATE = 0x04


class ECSearchType(Enum):
    EC_SEARCH_LOCAL = 0x00
    EC_SEARCH_GLOBAL = 0x01
    EC_SEARCH_KAD = 0x02
    EC_SEARCH_WEB = 0x03


class EcPrefs(Enum):
    """Selector de preferencias para ``EC_OP_GET_PREFERENCES``."""

    EC_PREFS_CATEGORIES = 0x00000001
    EC_PREFS_GENERAL = 0x00000002
    EC_PREFS_CONNECTIONS = 0x00000004
    EC_PREFS_MESSAGEFILTER = 0x00000008
    EC_PREFS_REMOTECONTROLS = 0x00000010
    EC_PREFS_ONLINESIG = 0x00000020
    EC_PREFS_SERVERS = 0x00000040
    EC_PREFS_FILES = 0x00000080
    EC_PREFS_DIRECTORIES = 0x00000200
    EC_PREFS_STATISTICS = 0x00000400
    EC_PREFS_SECURITY = 0x00000800
    EC_PREFS_CORETWEAKS = 0x00001000
    EC_PREFS_KADEMLIA = 0x00002000


class ECTagType(Enum):
    """Tipo de dato del valor de un tag."""

    EC_TAGTYPE_UNKNOWN = 0
    EC_TAGTYPE_CUSTOM = 1
    EC_TAGTYPE_UINT8 = 2
    EC_TAGTYPE_UINT16 = 3
    EC_TAGTYPE_UINT32 = 4
    EC_TAGTYPE_UINT64 = 5
    EC_TAGTYPE_STRING = 6
    EC_TAGTYPE_DOUBLE = 7
    EC_TAGTYPE_IPV4 = 8
    EC_TAGTYPE_HASH16 = 9
    EC_TAGTYPE_UINT128 = 10

    @classmethod
    def from_value(cls, value: int) -> "ECTagType":
        try:
            return cls(value)
        except ValueError:
            return cls.EC_TAGTYPE_UNKNOWN


class ECSearchFileDownloadStatus(Enum):
    """Estado de descarga de un fichero en resultados de búsqueda."""

    NEW = 0  # desconocido
    DOWNLOADED = 1  # descargado o compartido con éxito
    QUEUED = 2  # descargando (Partfile)
    CANCELED = 3  # cancelado
    QUEUEDCANCELED = 4  # cancelado una vez, ahora descargando de nuevo
